# Source this file to use the function `gpu_count`: source path/gpu_count.sh
# Returns the number of GPUs that should be used on on current node.
# [This function was generated by GPT-5.2]


gpu_count() {
  # 1) Scheduler-provided device visibility (most reliable on clusters)
  if [[ -n "${CUDA_VISIBLE_DEVICES:-}" ]]; then
    local v="${CUDA_VISIBLE_DEVICES}"
    v="${v// /}" # strip spaces
    if [[ -z "$v" ]]; then
      echo 1
      return
    fi
    local count=0
    IFS=',' read -ra parts <<< "$v"
    for p in "${parts[@]}"; do
      [[ -n "$p" ]] && ((count++))
    done
    echo "${count:-1}"
    return
  fi

  # 2) Slurm hints (varies by cluster)
  if [[ -n "${SLURM_GPUS_ON_NODE:-}" ]]; then
    echo "$SLURM_GPUS_ON_NODE"; return
  fi
  if [[ -n "${SLURM_GPUS_PER_NODE:-}" ]]; then
    # Often like "4" or "gpu:4" or "gpu:rtx6000:4"
    echo "$SLURM_GPUS_PER_NODE" | sed -E 's/.*:([0-9]+)$/\1/'; return
  fi
  if [[ -n "${SLURM_JOB_GPUS:-}" ]]; then
    # Usually a list of GPU IDs
    local v="${SLURM_JOB_GPUS// /}"
    local count=0
    IFS=',' read -ra parts <<< "$v"
    for p in "${parts[@]}"; do
      [[ -n "$p" ]] && ((count++))
    done
    echo "${count:-1}"; return
  fi

  # 3) Local machine fallback
  if command -v nvidia-smi >/dev/null 2>&1; then
    local count
    count="$(nvidia-smi -L 2>/dev/null | wc -l)"
    echo "${count:-1}"
    return
  fi

  echo 1
}
